StraaS/StraaS-android-sdk-sample

- CHANGELOG.md
- Messaging/build.gradle
- gradle.properties
> feat: enable vector drawable

- CHANGELOG.md
- README.md
- gradle.properties
> feat: CHNAGELOG for v0.3.4

- README.md
> improvement: README

- CHANGELOG.md
- Messaging/src/main/res/values/styles.xml
- gradle.properties
> feat: release v0.3.9

- ISSUE_TEMPLATE.md
add issue template for android
> docs: issue template

- CHANGELOG.md
- gradle.properties
> feat: release v0.3.11

- CHANGELOG.md
- build.gradle
- gradle.properties
> feat: v0.4.4

- CHANGELOG.md
> feat: fix changlog

- CHANGELOG.md
- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/MainActivity.java
- Streaming/src/main/res/layout/activity_main.xml
- Streaming/src/main/res/values/styles.xml
- gradle.properties
> feat: v0.5.2

- Streaming/build.gradle
> fix: rename application id

- CHANGELOG.md
- gradle.properties
> feat: v0.5.5

- CHANGELOG.md
- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/MainActivity.java
- Streaming/src/main/res/layout/activity_main.xml
- gradle.properties
> feat: v0.5.7

- CHANGELOG.md
description for reuseLiveEvent flag
> description for reuseLiveEvent flag

- CHANGELOG.md
- gradle.properties
> feat: v0.7.0

- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/MainActivity.java
> Use StreamConfig.Builder

- MediaCore/src/main/java/io/straas/android/media/demo/OperationActivity.java
- MediaCore/src/main/res/layout/activity_operation.xml
Use low latency first switch UI to select to play HLS or RTMP stream type
> feat: Add low latency first switch

- MediaCore/src/main/java/io/straas/android/media/demo/MediaControllerCompatHelper.java
- MediaCore/src/main/java/io/straas/android/media/demo/OperationActivity.java
- MediaCore/src/main/java/io/straas/android/media/demo/widget/StraasPlayerView.java
- MediaCore/src/main/res/layout/activity_operation.xml
- app/src/main/AndroidManifest.xml
> feat: foreground play

- MediaCore/src/main/java/io/straas/android/media/demo/OperationActivity.java
> refactor: simplify check

- Messaging/src/main/res/values/styles.xml
fix: add lost attribute for ChatroomTheme
> fix: add lost attribute for ChatroomTheme

- build.gradle
https://bintray.com/android/android-tools/com.android.tools.build.gradle/2.3.2
> feat: android gradle plugin 2.3.2

- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/Utils.java
- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/camera/MainActivity.java
- Streaming/src/main/res/layout/activity_main_streaming.xml
- Streaming/src/main/res/values/strings.xml
1. Add stats update ui in the right, bottom corner
2. UI style ref: [ios_stream_stats](https://redmine.livehouse.in/attachments/download/6617/demo_app_streaming_stats.png)
3. formatBitrate refs: [Formatter](https://android.googlesource.com/platform/frameworks/base/+/ics-mr1/core/java/android/text/format/Formatter.java#47)
> feat: add streaming ui for camera and sync the style with iOS.

- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/Utils.java
- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/camera/MainActivity.java
- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/screencast/MyScreencastSession.java
- Streaming/src/main/res/layout/activity_main_streaming.xml
- Streaming/src/main/res/values/strings.xml
update streaming EventListener API for `camera and screencast streaming`
> fix: update streaming EventListener API

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Upgrade build tool version to 3.0.0
> Upgrade build tool version to 3.0.0

- CHANGELOG.md
- gradle.properties
> feat: v0.8.6

- MediaCore/src/main/java/io/straas/android/media/demo/widget/StraasPlayerView.java
- Streaming/src/main/java/io/straas/android/sdk/streaming/demo/camera/MainActivity.java
> Use BROADCAST_STATE_V2.

- MediaCore/src/main/java/io/straas/android/media/demo/widget/StraasPlayerView.java
fix: Adjust logic for broadcast state ui.
> fix: Adjust logic for broadcast state ui.

- MediaCore/src/main/res/values/strings.xml
fix mis removing en string key
> fix: missing en quality_select string key and remove unused quality_high
